name: Test build Docker image
on:
  pull_request:
  workflow_dispatch:
  push:
    branches-ignore:
      - master
jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: docker build .
